language: node_js

node_js:
  - "5"
  - "4.2"

sudo: false

script:
 - "npm test"

deploy:
  provider: openshift
  user: "mohammed.elbouzrouti@orange.com"
  password: "Azlaf@1989"
  domain: "orangegroup"
  app: privacy
