language: node_js

node_js:
  - '5'
  - '0.10'

sudo: false

script:
 - "npm test"
deploy:
  provider: openshift
  user: "mohammed.elbouzrouti@gmail.com"
  password: "Azlaf0000"
  domain: "orangegroup"
  app:
    master: privacy

